FROM python:3.5

COPY requirements.txt requirements-test.txt /opt/project/

WORKDIR /opt/project

RUN pip install -r requirements.txt -r requirements-test.txt

COPY . /opt/project

RUN pip install -e .

COPY docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/bin/bash"]
