FROM ubuntu:trusty

RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list && \
	echo "deb http://archive.ubuntu.com/ubuntu trusty-updates main universe" >>/etc/apt/sources.list && \
	echo "deb http://archive.ubuntu.com/ubuntu trusty-security main universe" >>/etc/apt/sources.list && \
	apt-get update && \
	apt-get install -qq -y openssl software-properties-common && \
	add-apt-repository ppa:fkrull/deadsnakes && \
	apt-get update && \
	apt-get install -qq -y python2.6 python2.6-dev wget make && \
	(cd /tmp && wget https://bootstrap.pypa.io/get-pip.py && python2.6 get-pip.py && rm get-pip.py) && \
	apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

COPY requirements.txt requirements-test.txt /opt/project/

WORKDIR /opt/project

RUN pip install -r requirements.txt -r requirements-test.txt

COPY . /opt/project

RUN pip install -e .

COPY docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/bin/bash"]
